---
# tasks file for sbaerlocher.local-group-policy

- name: Create temporary directory for GroupPolicy
  tempfile:
    state: directory
  register: register_local_group_policy_temporary
  delegate_to: 127.0.0.1
  tags:
    - configuration

- name: Set fact for temporary path
  set_fact:
    local_group_policy_temporary: "{{ register_local_group_policy_temporary.path }}"
  tags:
    - configuration

- name: Git clone GroupPolicy
  git:
    repo: "{{ local_group_policy_repo }}"
    dest: "{{ local_group_policy_temporary }}"
    version: "{{ local_group_policy_branch | default('master') }}"
  delegate_to: 127.0.0.1
  tags:
    - configuration

- name: Copy GroupPolicy directory
  win_copy:
    src: "{{ local_group_policy_temporary }}"
    dest: "{{ local_group_policy_directory }}"
  tags:
    - configuration

- name: Remove temporary directory for GroupPolicy
  file:
    path: "{{ local_group_policy_temporary }}"
    state: absent
  delegate_to: 127.0.0.1
  tags:
    - configuration

- name: Update GroupPolicy
  win_shell: gpupdate /force
  tags:
    - configuration
